const  express = require('express');
const { Agent } = require('http');
const app = express();
const port = 3000;
var morgan = require('morgan')
var fs = require('fs')
var path = require('path')

const swaggerJsdoc = require('swagger-jsdoc')
const swaggerUi = require('swagger-ui-express');
const cors = require('cors');
app.use(express.json());
app.use(morgan(':method :url :status :res[content-length] - :response-time ms', {
  stream: fs.createWriteStream(path.join(__dirname, 'access.log'), { flags: 'a' })
}))
const options = {
  swaggerDefinition: {
   info: {
       title: 'Personal Budget API',
       version: '1.0.0',
       description: 'Personal Budget API autogenerated by Swagger'
   },
   host: '159.89.225.232:3000',
   basePath: '/',
  },
  apis: ['./requests.js'],
};

app.use(cors());
const specs = swaggerJsdoc(options);
app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));
require('./requests')(app);
app.listen(port,  () => {
  console.log('server is listening at http://localhost:'+port)
});